version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/todoapp
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reversi
    ports:
      - "5432:5432"
    volumes:
      - reversi_db:/var/lib/postgresql/data
volumes:
  reversi_db: